package com.soulderspace.souldercontent.forge;

import com.soulderspace.souldercontent.block.SoulderBlocks;
import com.soulderspace.souldercontent.item.SoulderItems;
import com.soulderspace.souldercontent.SoulderContent;
import net.minecraft.item.ItemGroup;
import net.minecraft.registry.Registries;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.RegisterEvent;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@Mod(SoulderContent.ID)
public class SoulderContentForge {
    private static final Logger LOGGER = LogManager.getLogger(SoulderContentForge.class);
    public SoulderContentForge() {

        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::registerBlocks);
        FMLJavaModLoadingContext.get().getModEventBus().addListener(this::registerItems);
        SoulderContent.init();
    }

    @SubscribeEvent
    public void registerItems(RegisterEvent event) {
        SoulderItems items = SoulderItems.getInstance();

        // Регистрация первой группы предметов (основная группа)
        event.register(items.getRegistryKey(), helper -> items.register(helper::register));
        event.register(
                Registries.ITEM_GROUP.getKey(), helper -> helper.register(new Identifier(SoulderContent.ID, "soulder_content"),
                        ItemGroup.builder()
                                .displayName(Text.translatable("itemGroup.souldercontent"))
                                .icon(items.ENVELOPE::getDefaultStack)  // Иконка для первой вкладки
                                .entries((displayContext, entries) -> items.all().forEach(item -> entries.add(item.getDefaultStack())))
                                .build())
        );

        // Регистрация новой боковой вкладки-массива
        event.register(
                Registries.ITEM_GROUP.getKey(), helper -> helper.register(new Identifier(SoulderContent.ID, "soulder_content_items"),
                        ItemGroup.builder()
                                .displayName(Text.translatable("itemGroup.souldercontent.items"))  // Название новой вкладки
                                .icon(items.DITTO_COIN::getDefaultStack)  // Иконка
                                .entries((displayContext, entries) -> {
                                    // Добавляем предметы по их ID
                                    Identifier[] itemIDs = new Identifier[] {
                                            new Identifier(SoulderContent.ID, "normal_key"),
                                            new Identifier(SoulderContent.ID, "medium_key"),
                                            new Identifier(SoulderContent.ID, "premium_key"),
                                            new Identifier(SoulderContent.ID, "halloween_key"),
                                            new Identifier(SoulderContent.ID, "black_silver_key"),
                                            new Identifier(SoulderContent.ID, "blue_light_blue_key"),
                                            new Identifier(SoulderContent.ID, "brown_silver_key"),
                                            new Identifier(SoulderContent.ID, "pink_green_key"),
                                            new Identifier(SoulderContent.ID, "purple_light_purple_key"),
                                            new Identifier(SoulderContent.ID, "red_golden_key"),
                                            new Identifier(SoulderContent.ID, "aegis_badge"),
                                            new Identifier(SoulderContent.ID, "aphid_badge"),
                                            new Identifier(SoulderContent.ID, "blight_badge"),
                                            new Identifier(SoulderContent.ID, "crest_badge"),
                                            new Identifier(SoulderContent.ID, "dewdrop_badge"),
                                            new Identifier(SoulderContent.ID, "esper_badge"),
                                            new Identifier(SoulderContent.ID, "fable_badge"),
                                            new Identifier(SoulderContent.ID, "garden_badge"),
                                            new Identifier(SoulderContent.ID, "glacier_badge"),
                                            new Identifier(SoulderContent.ID, "harmony_badge"),
                                            new Identifier(SoulderContent.ID, "inferno_badge"),
                                            new Identifier(SoulderContent.ID, "master_badge"),
                                            new Identifier(SoulderContent.ID, "melee_badge"),
                                            new Identifier(SoulderContent.ID, "mythos_badge"),
                                            new Identifier(SoulderContent.ID, "phantom_badge"),
                                            new Identifier(SoulderContent.ID, "quarry_badge"),
                                            new Identifier(SoulderContent.ID, "sand_badge"),
                                            new Identifier(SoulderContent.ID, "tesla_badge"),
                                            new Identifier(SoulderContent.ID, "suspicious_rubber"),
                                            new Identifier(SoulderContent.ID, "suspicious_cloth"),
                                            new Identifier(SoulderContent.ID, "suspicious_string"),
                                            new Identifier(SoulderContent.ID, "envelope"),
                                            new Identifier(SoulderContent.ID, "bulba_coin"),
                                            new Identifier(SoulderContent.ID, "g.coin"),
                                            new Identifier(SoulderContent.ID, "c.coin_1"),
                                            new Identifier(SoulderContent.ID, "supercoin"),
                                            new Identifier(SoulderContent.ID, "shiny"),
                                            new Identifier(SoulderContent.ID, "copper_coincabu"),
                                            new Identifier(SoulderContent.ID, "fullmetal_coincabu"),
                                            new Identifier(SoulderContent.ID, "golden_coincabu"),
                                            new Identifier(SoulderContent.ID, "ditto_coin"),
                                            new Identifier(SoulderContent.ID, "ticket"),
                                            new Identifier(SoulderContent.ID, "fdefender_sword"),
                                            new Identifier(SoulderContent.ID, "wilt_sword"),
                                            new Identifier(SoulderContent.ID, "pokehats/brendanhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/calemhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/calemhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/dawnhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/dawnhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/eliohat"),
                                            new Identifier(SoulderContent.ID, "pokehats/eliohatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/gloriahat"),
                                            new Identifier(SoulderContent.ID, "pokehats/gloriahatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/goldhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/goldhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/goomyhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/hilberthat"),
                                            new Identifier(SoulderContent.ID, "pokehats/hilberthatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/hildahat"),
                                            new Identifier(SoulderContent.ID, "pokehats/hoppiphat"),
                                            new Identifier(SoulderContent.ID, "pokehats/krishat"),
                                            new Identifier(SoulderContent.ID, "pokehats/leafhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/leafhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/lucashat"),
                                            new Identifier(SoulderContent.ID, "pokehats/lucashatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/mayhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/mayhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/natehat"),
                                            new Identifier(SoulderContent.ID, "pokehats/natehatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/psycap"),
                                            new Identifier(SoulderContent.ID, "pokehats/redhat"),
                                            new Identifier(SoulderContent.ID, "pokehats/redhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/rosahat"),
                                            new Identifier(SoulderContent.ID, "pokehats/rosahatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/selenehat"),
                                            new Identifier(SoulderContent.ID, "pokehats/selenehatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/serenahatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/sylveonears"),
                                            new Identifier(SoulderContent.ID, "pokehats/umbreoncap"),
                                            new Identifier(SoulderContent.ID, "pokehats/victorhatnh"),
                                            new Identifier(SoulderContent.ID, "pokehats/witch_hat"),
                                            new Identifier(SoulderContent.ID, "pokehats/victorhat")

                                            // добавьте остальные ID по необходимости
                                    };

                                    for (Identifier itemID : itemIDs) {
                                        var item = Registries.ITEM.get(itemID);

                                        // Проверяем, что предмет существует, прежде чем добавлять его
                                        if (item != null) {
                                            entries.add(item.getDefaultStack());
//                                            LOGGER.warn("Предмет с ID " + itemID + " не найден в реестре.");
                                        }
                                    }
                                })
                                .build())
        );
        event.register(
                Registries.ITEM_GROUP.getKey(), helper -> helper.register(new Identifier(SoulderContent.ID, "soulder_content_blocks_crates"),
                        ItemGroup.builder()
                                .displayName(Text.translatable("itemGroup.souldercontent.blocks_crates"))  // Название новой вкладки
                                .icon(items.SCARECROW_3_TOP::getDefaultStack)  // Иконка
                                .entries((displayContext, entries) -> {
                                    // Добавляем предметы по их ID
                                    Identifier[] itemIDs = new Identifier[] {
                                            new Identifier(SoulderContent.ID, "normal_chest"),
                                            new Identifier(SoulderContent.ID, "medium_chest"),
                                            new Identifier(SoulderContent.ID, "premium_chest"),
                                            new Identifier(SoulderContent.ID, "halloween_crate"),
                                            new Identifier(SoulderContent.ID, "black_silver_crate"),
                                            new Identifier(SoulderContent.ID, "blue_light_blue_crate"),
                                            new Identifier(SoulderContent.ID, "brown_silver_crate"),
                                            new Identifier(SoulderContent.ID, "pink_green_crate"),
                                            new Identifier(SoulderContent.ID, "purple_light_purple_crate"),
                                            new Identifier(SoulderContent.ID, "red_golden_crate"),
                                            new Identifier(SoulderContent.ID, "autumn_leaves_carpet_0"),
                                            new Identifier(SoulderContent.ID, "spiderweb_0"),
                                            new Identifier(SoulderContent.ID, "spiderweb_1"),
                                            new Identifier(SoulderContent.ID, "spiderweb_2"),
                                            new Identifier(SoulderContent.ID, "spiderweb_3"),
                                            new Identifier(SoulderContent.ID, "spiderweb_4"),
                                            new Identifier(SoulderContent.ID, "skeleton_0"),
                                            new Identifier(SoulderContent.ID, "skeleton_1"),
                                            new Identifier(SoulderContent.ID, "skeleton_2"),
                                            new Identifier(SoulderContent.ID, "skeleton_3"),
                                            new Identifier(SoulderContent.ID, "skeleton_4"),
                                            new Identifier(SoulderContent.ID, "scarecrow_0_top"),
                                            new Identifier(SoulderContent.ID, "scarecrow_1_top"),
                                            new Identifier(SoulderContent.ID, "scarecrow_2_top"),
                                            new Identifier(SoulderContent.ID, "scarecrow_3_top"),
                                            new Identifier(SoulderContent.ID, "scarecrow_4_top"),
                                            new Identifier(SoulderContent.ID, "scarecrow_0_bottom"),
                                            new Identifier(SoulderContent.ID, "scarecrow_1_bottom"),
                                            new Identifier(SoulderContent.ID, "scarecrow_2_bottom"),
                                            new Identifier(SoulderContent.ID, "scarecrow_3_bottom"),
                                            new Identifier(SoulderContent.ID, "scarecrow_4_bottom"),
                                            new Identifier(SoulderContent.ID, "carved_evil_pumpkin"),
                                            new Identifier(SoulderContent.ID, "carved_friendly_pumpkin"),
                                            new Identifier(SoulderContent.ID, "carved_screaming_pumpkin"),
                                            new Identifier(SoulderContent.ID, "carved_shocked_pumpkin"),
                                            new Identifier(SoulderContent.ID, "carved_smile_pumpkin"),
                                            new Identifier(SoulderContent.ID, "hay_wheelbarrow"),
                                            new Identifier(SoulderContent.ID, "laying_hay_bale"),
                                            new Identifier(SoulderContent.ID, "pumpkin_wheelbarrow"),
                                            new Identifier(SoulderContent.ID, "large_pumpkin"),
                                            new Identifier(SoulderContent.ID, "small_pumpkin"),
                                            new Identifier(SoulderContent.ID, "medium_pumpkin"),
                                            new Identifier(SoulderContent.ID, "lit_evil_pumpkin"),
                                            new Identifier(SoulderContent.ID, "lit_friendly_pumpkin"),
                                            new Identifier(SoulderContent.ID, "lit_screaming_pumpkin"),
                                            new Identifier(SoulderContent.ID, "lit_shocked_pumpkin"),
                                            new Identifier(SoulderContent.ID, "lit_smile_pumpkin"),
                                            new Identifier(SoulderContent.ID, "pair_of_pumpkins"),
                                            new Identifier(SoulderContent.ID, "pumpkin_balloon"),
                                            new Identifier(SoulderContent.ID, "pumpkin_wall_deco_1"),
                                            new Identifier(SoulderContent.ID, "pumpkin_wall_deco_2"),
                                            new Identifier(SoulderContent.ID, "scarecrow"),
                                            new Identifier(SoulderContent.ID, "sitting_skeleton"),
                                            new Identifier(SoulderContent.ID, "skeleton_balloon"),
                                            new Identifier(SoulderContent.ID, "ghost_balloon"),
                                            new Identifier(SoulderContent.ID, "ghost"),
                                            new Identifier(SoulderContent.ID, "three_potions"),
                                            new Identifier(SoulderContent.ID, "three_pumpkins"),
                                            new Identifier(SoulderContent.ID, "witch_cauldron"),
                                            new Identifier(SoulderContent.ID, "flat_dirt_gravestone"),
                                            new Identifier(SoulderContent.ID, "flat_gravestone"),
                                            new Identifier(SoulderContent.ID, "gravestone"),
                                            new Identifier(SoulderContent.ID, "slanted_gravestone"),
                                            new Identifier(SoulderContent.ID, "square_gravestone"),
                                            new Identifier(SoulderContent.ID, "small_gravestone")



                                            // добавьте остальные ID по необходимости
                                    };

                                    for (Identifier itemID : itemIDs) {
                                        var item = Registries.ITEM.get(itemID);

                                        // Проверяем, что предмет существует, прежде чем добавлять его
                                        if (item != null) {
                                            entries.add(item.getDefaultStack());

//                                            LOGGER.warn("Предмет с ID " + itemID + " не найден в реестре.");
                                        }
                                    }
                                })
                                .build())
        );
        event.register(
                Registries.ITEM_GROUP.getKey(), helper -> helper.register(new Identifier(SoulderContent.ID, "soulder_content_side_tab"),
                        ItemGroup.builder()
                                .displayName(Text.translatable("itemGroup.souldercontent.plushies"))  // Название новой вкладки
                                .icon(items.ZOMBIEFIED_PIGLIN_PLUSHIE::getDefaultStack)  // Иконка
                                .entries((displayContext, entries) -> {
                                    // Добавляем предметы по их ID
                                    Identifier[] itemIDs = new Identifier[] {
                                            new Identifier(SoulderContent.ID, "pokedoll_meloetta_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_meloetta"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mewtwo_gilded_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mewtwo_gilded"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zubat_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zubat"),
                                            new Identifier(SoulderContent.ID, "zombified_piglin_plushie"),
                                            new Identifier(SoulderContent.ID, "pokedoll_big_giratina"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cubone"),
                                            new Identifier(SoulderContent.ID, "pokedoll_espeon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gengar"),
                                            new Identifier(SoulderContent.ID, "pokedoll_golbat"),
                                            new Identifier(SoulderContent.ID, "pokedoll_houndoom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_litwick"),
                                            new Identifier(SoulderContent.ID, "pokedoll_houndour"),
                                            new Identifier(SoulderContent.ID, "pokedoll_marowak"),
                                            new Identifier(SoulderContent.ID, "pokedoll_umbreon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zorua"),
                                            new Identifier(SoulderContent.ID, "pokedoll_big_giratina_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cubone_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_espeon_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gengar_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_golbat_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_houndoom_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_litwick_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_houndour_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_marowak_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_umbreon_shiny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zorua_shiny"),
                                            //388 плюшей ниже
                                            new Identifier(SoulderContent.ID, "pokedoll_abra"),
                                            new Identifier(SoulderContent.ID, "pokedoll_aerodactyl"),
                                            new Identifier(SoulderContent.ID, "pokedoll_aipom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ampharos"),
                                            new Identifier(SoulderContent.ID, "pokedoll_applin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_arbok"),
                                            new Identifier(SoulderContent.ID, "pokedoll_arctibax"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ariados"),
                                            new Identifier(SoulderContent.ID, "pokedoll_aron"),
                                            new Identifier(SoulderContent.ID, "pokedoll_azumarill"),
                                            new Identifier(SoulderContent.ID, "pokedoll_baltoy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bayleef"),
                                            new Identifier(SoulderContent.ID, "pokedoll_beldum"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bellibolt"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bellsprout"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bibarel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bidoof"),
                                            new Identifier(SoulderContent.ID, "pokedoll_big_dialga"),
                                            new Identifier(SoulderContent.ID, "pokedoll_big_hooh"),
                                            new Identifier(SoulderContent.ID, "pokedoll_big_palkia"),
                                            new Identifier(SoulderContent.ID, "pokedoll_blastoise"),
                                            new Identifier(SoulderContent.ID, "pokedoll_blitzle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bonsly"),
                                            new Identifier(SoulderContent.ID, "pokedoll_breloom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_buizel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bulbasaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_buneary"),
                                            new Identifier(SoulderContent.ID, "pokedoll_bunnelby"),
                                            new Identifier(SoulderContent.ID, "pokedoll_burmy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_butterfree"),
                                            new Identifier(SoulderContent.ID, "pokedoll_camerupt"),
                                            new Identifier(SoulderContent.ID, "pokedoll_capsakid"),
                                            new Identifier(SoulderContent.ID, "pokedoll_castform"),
                                            new Identifier(SoulderContent.ID, "pokedoll_castform_sunny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_caterpie"),
                                            new Identifier(SoulderContent.ID, "pokedoll_celebi"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cetoddle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_charizard"),
                                            new Identifier(SoulderContent.ID, "pokedoll_charmander"),
                                            new Identifier(SoulderContent.ID, "pokedoll_charmeleon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chatot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cherubi"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chespin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chienpao"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chikorita"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chimchar"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chinchou"),
                                            new Identifier(SoulderContent.ID, "pokedoll_chiyu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_clefable"),
                                            new Identifier(SoulderContent.ID, "pokedoll_clefairy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cleffa"),
                                            new Identifier(SoulderContent.ID, "pokedoll_clodsire"),
                                            new Identifier(SoulderContent.ID, "pokedoll_combusken"),
                                            new Identifier(SoulderContent.ID, "pokedoll_crocalor"),
                                            new Identifier(SoulderContent.ID, "pokedoll_croconaw"),
                                            new Identifier(SoulderContent.ID, "pokedoll_cyndaquil"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dachsbun"),
                                            new Identifier(SoulderContent.ID, "pokedoll_darumaka"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dedenne"),
                                            new Identifier(SoulderContent.ID, "pokedoll_delcatty"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dewgong"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dewott"),
                                            new Identifier(SoulderContent.ID, "pokedoll_diglett"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dipplin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ditto"),
                                            new Identifier(SoulderContent.ID, "pokedoll_doduo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dondozo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dragonair"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dragonite"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dratini"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dreepy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_drilbur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_drowzee"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ducklett"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dugtrio"),
                                            new Identifier(SoulderContent.ID, "pokedoll_dunsparce"),
                                            new Identifier(SoulderContent.ID, "pokedoll_eevee"),
                                            new Identifier(SoulderContent.ID, "pokedoll_eiscue"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ekans"),
                                            new Identifier(SoulderContent.ID, "pokedoll_electrode"),
                                            new Identifier(SoulderContent.ID, "pokedoll_elekid"),
                                            new Identifier(SoulderContent.ID, "pokedoll_elgyem"),
                                            new Identifier(SoulderContent.ID, "pokedoll_espurr"),
                                            new Identifier(SoulderContent.ID, "pokedoll_excadrill"),
                                            new Identifier(SoulderContent.ID, "pokedoll_exeggcute"),
                                            new Identifier(SoulderContent.ID, "pokedoll_exeggutor"),
                                            new Identifier(SoulderContent.ID, "pokedoll_farigiraf"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fearow"),
                                            new Identifier(SoulderContent.ID, "pokedoll_female_nidoran"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fennekin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_feraligatr"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fidough"),
                                            new Identifier(SoulderContent.ID, "pokedoll_finizen"),
                                            new Identifier(SoulderContent.ID, "pokedoll_finneon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_flaaffy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_flamigo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_flareon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fletchinder"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fletchling"),
                                            new Identifier(SoulderContent.ID, "pokedoll_floatzel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_flygon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_frigibax"),
                                            new Identifier(SoulderContent.ID, "pokedoll_froakie"),
                                            new Identifier(SoulderContent.ID, "pokedoll_frogadier"),
                                            new Identifier(SoulderContent.ID, "pokedoll_fuecoco"),
                                            new Identifier(SoulderContent.ID, "pokedoll_furret"),
                                            new Identifier(SoulderContent.ID, "pokedoll_garbodor"),
                                            new Identifier(SoulderContent.ID, "pokedoll_geodude"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gholdengo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_girafarig"),
                                            new Identifier(SoulderContent.ID, "pokedoll_glastrier"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gloom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_golduck"),
                                            new Identifier(SoulderContent.ID, "pokedoll_golem"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gothita"),
                                            new Identifier(SoulderContent.ID, "pokedoll_grafaiai"),
                                            new Identifier(SoulderContent.ID, "pokedoll_granbull"),
                                            new Identifier(SoulderContent.ID, "pokedoll_graveler"),
                                            new Identifier(SoulderContent.ID, "pokedoll_greedent"),
                                            new Identifier(SoulderContent.ID, "pokedoll_grookey"),
                                            new Identifier(SoulderContent.ID, "pokedoll_groudon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_groudon_gilded"),
                                            new Identifier(SoulderContent.ID, "pokedoll_grovyle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_growlithe"),
                                            new Identifier(SoulderContent.ID, "pokedoll_grubbin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_grumpig"),
                                            new Identifier(SoulderContent.ID, "pokedoll_gulpin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_halloween_bulbasaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_halloween_ivysaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_halloween_venusaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_heracross"),
                                            new Identifier(SoulderContent.ID, "pokedoll_hitmonlee"),
                                            new Identifier(SoulderContent.ID, "pokedoll_hooh"),
                                            new Identifier(SoulderContent.ID, "pokedoll_hoothoot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_hoppip"),
                                            new Identifier(SoulderContent.ID, "pokedoll_hypno"),
                                            new Identifier(SoulderContent.ID, "pokedoll_igglybuff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_impidimp"),
                                            new Identifier(SoulderContent.ID, "pokedoll_iron_bundle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ironvaliant"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ivysaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_jigglypuff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_jirachi"),
                                            new Identifier(SoulderContent.ID, "pokedoll_jolteon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_kilowattrel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_koraidon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_kricketot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_krokorok"),
                                            new Identifier(SoulderContent.ID, "pokedoll_krookodile"),
                                            new Identifier(SoulderContent.ID, "pokedoll_kyogre"),
                                            new Identifier(SoulderContent.ID, "pokedoll_kyogre_gilded"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lanturn"),
                                            new Identifier(SoulderContent.ID, "pokedoll_larvitar"),
                                            new Identifier(SoulderContent.ID, "pokedoll_latias"),
                                            new Identifier(SoulderContent.ID, "pokedoll_latios"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lechonk"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ledian"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ledyba"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lillipup"),
                                            new Identifier(SoulderContent.ID, "pokedoll_linoone"),
                                            new Identifier(SoulderContent.ID, "pokedoll_litleo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_litten"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lotad"),
                                            new Identifier(SoulderContent.ID, "pokedoll_loudred"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lucario"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lugia"),
                                            new Identifier(SoulderContent.ID, "pokedoll_lumineon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_luxio"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mabosstiff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_machop"),
                                            new Identifier(SoulderContent.ID, "pokedoll_magby"),
                                            new Identifier(SoulderContent.ID, "pokedoll_magcargo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_magikarp"),
                                            new Identifier(SoulderContent.ID, "pokedoll_magnemite"),
                                            new Identifier(SoulderContent.ID, "pokedoll_male_nidoran"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mamoswine"),
                                            new Identifier(SoulderContent.ID, "pokedoll_manaphy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mankey"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mantine"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mantyke"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mareep"),
                                            new Identifier(SoulderContent.ID, "pokedoll_marill"),
                                            new Identifier(SoulderContent.ID, "pokedoll_marshtomp"),
                                            new Identifier(SoulderContent.ID, "pokedoll_maschiff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_masquerain"),
                                            new Identifier(SoulderContent.ID, "pokedoll_meditite"),
                                            new Identifier(SoulderContent.ID, "pokedoll_meganium"),
                                            new Identifier(SoulderContent.ID, "pokedoll_meowth"),
                                            new Identifier(SoulderContent.ID, "pokedoll_metagross"),
                                            new Identifier(SoulderContent.ID, "pokedoll_metang"),
                                            new Identifier(SoulderContent.ID, "pokedoll_metapod"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mew"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mewtwo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_miltank"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mime_jr"),
                                            new Identifier(SoulderContent.ID, "pokedoll_minccino"),
                                            new Identifier(SoulderContent.ID, "pokedoll_minior"),
                                            new Identifier(SoulderContent.ID, "pokedoll_minun"),
                                            new Identifier(SoulderContent.ID, "pokedoll_miraidon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_monferno"),
                                            new Identifier(SoulderContent.ID, "pokedoll_morpeko"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mr_mime"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mr_rime"),
                                            new Identifier(SoulderContent.ID, "pokedoll_mudkip"),
                                            new Identifier(SoulderContent.ID, "pokedoll_munna"),
                                            new Identifier(SoulderContent.ID, "pokedoll_murkrow"),
                                            new Identifier(SoulderContent.ID, "pokedoll_nacli"),
                                            new Identifier(SoulderContent.ID, "pokedoll_natu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_nickit"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ninetales"),
                                            new Identifier(SoulderContent.ID, "pokedoll_noctowl"),
                                            new Identifier(SoulderContent.ID, "pokedoll_numel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_nuzleaf"),
                                            new Identifier(SoulderContent.ID, "pokedoll_octillery"),
                                            new Identifier(SoulderContent.ID, "pokedoll_oddish"),
                                            new Identifier(SoulderContent.ID, "pokedoll_oinkologne"),
                                            new Identifier(SoulderContent.ID, "pokedoll_orthworm"),
                                            new Identifier(SoulderContent.ID, "pokedoll_oshawott"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pachirisu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_panpour"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pansage"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pansear"),
                                            new Identifier(SoulderContent.ID, "pokedoll_paras"),
                                            new Identifier(SoulderContent.ID, "pokedoll_parasect"),
                                            new Identifier(SoulderContent.ID, "pokedoll_patrat"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pawmi"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pawmo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pawmot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_persian"),
                                            new Identifier(SoulderContent.ID, "pokedoll_phanpy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_phione"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pichu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pidgeotto"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pidgey"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pidove"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pignite"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pikachu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_pikipek"),
                                            new Identifier(SoulderContent.ID, "pokedoll_piloswine"),
                                            new Identifier(SoulderContent.ID, "pokedoll_piplup"),
                                            new Identifier(SoulderContent.ID, "pokedoll_plusle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_politoed"),
                                            new Identifier(SoulderContent.ID, "pokedoll_poliwag"),
                                            new Identifier(SoulderContent.ID, "pokedoll_poliwhirl"),
                                            new Identifier(SoulderContent.ID, "pokedoll_poliwrath"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ponyta"),
                                            new Identifier(SoulderContent.ID, "pokedoll_poochyena"),
                                            new Identifier(SoulderContent.ID, "pokedoll_popplio"),
                                            new Identifier(SoulderContent.ID, "pokedoll_porygon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_porygon_2"),
                                            new Identifier(SoulderContent.ID, "pokedoll_primeape"),
                                            new Identifier(SoulderContent.ID, "pokedoll_prinplup"),
                                            new Identifier(SoulderContent.ID, "pokedoll_psyduck"),
                                            new Identifier(SoulderContent.ID, "pokedoll_quagsire"),
                                            new Identifier(SoulderContent.ID, "pokedoll_quaxly"),
                                            new Identifier(SoulderContent.ID, "pokedoll_quilava"),
                                            new Identifier(SoulderContent.ID, "pokedoll_quilladin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_qwilfish"),
                                            new Identifier(SoulderContent.ID, "pokedoll_raichu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ralts"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rapidash"),
                                            new Identifier(SoulderContent.ID, "pokedoll_raticate"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rattata"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rayquaza"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rayquaza_gilded"),
                                            new Identifier(SoulderContent.ID, "pokedoll_registeel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rellor"),
                                            new Identifier(SoulderContent.ID, "pokedoll_remoraid"),
                                            new Identifier(SoulderContent.ID, "pokedoll_riolu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_roaringmoon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rockruff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_roggenrola"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rookidee"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rotom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_rowlet"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sableye"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sandile"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sandshrew"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sandslash"),
                                            new Identifier(SoulderContent.ID, "pokedoll_scorbunny"),
                                            new Identifier(SoulderContent.ID, "pokedoll_scrafty"),
                                            new Identifier(SoulderContent.ID, "pokedoll_scraggy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_scream_tail"),
                                            new Identifier(SoulderContent.ID, "pokedoll_scyther"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sealeo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_seedot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_seel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sentret"),
                                            new Identifier(SoulderContent.ID, "pokedoll_servine"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sharpedo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_shaymin"),
                                            new Identifier(SoulderContent.ID, "pokedoll_shinx"),
                                            new Identifier(SoulderContent.ID, "pokedoll_shroodle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_shroomish"),
                                            new Identifier(SoulderContent.ID, "pokedoll_shuckle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_silcoon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_skiploom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_skitty"),
                                            new Identifier(SoulderContent.ID, "pokedoll_skwovet"),
                                            new Identifier(SoulderContent.ID, "pokedoll_slakoth"),
                                            new Identifier(SoulderContent.ID, "pokedoll_slowpoke"),
                                            new Identifier(SoulderContent.ID, "pokedoll_slugma"),
                                            new Identifier(SoulderContent.ID, "pokedoll_smeargle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_smoliv"),
                                            new Identifier(SoulderContent.ID, "pokedoll_smoochum"),
                                            new Identifier(SoulderContent.ID, "pokedoll_snivy"),
                                            new Identifier(SoulderContent.ID, "pokedoll_snorlax"),
                                            new Identifier(SoulderContent.ID, "pokedoll_snubbull"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sobble"),
                                            new Identifier(SoulderContent.ID, "pokedoll_solosis"),
                                            new Identifier(SoulderContent.ID, "pokedoll_spearow"),
                                            new Identifier(SoulderContent.ID, "pokedoll_spheal"),
                                            new Identifier(SoulderContent.ID, "pokedoll_spinarak"),
                                            new Identifier(SoulderContent.ID, "pokedoll_spinda"),
                                            new Identifier(SoulderContent.ID, "pokedoll_spoink"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sprigatito"),
                                            new Identifier(SoulderContent.ID, "pokedoll_squawkabilly"),
                                            new Identifier(SoulderContent.ID, "pokedoll_squirtle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_stantler"),
                                            new Identifier(SoulderContent.ID, "pokedoll_staravia"),
                                            new Identifier(SoulderContent.ID, "pokedoll_starly"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sudowoodo"),
                                            new Identifier(SoulderContent.ID, "pokedoll_suicune"),
                                            new Identifier(SoulderContent.ID, "pokedoll_sunflora"),
                                            new Identifier(SoulderContent.ID, "pokedoll_surskit"),
                                            new Identifier(SoulderContent.ID, "pokedoll_swablu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_swalot"),
                                            new Identifier(SoulderContent.ID, "pokedoll_swampert"),
                                            new Identifier(SoulderContent.ID, "pokedoll_swellow"),
                                            new Identifier(SoulderContent.ID, "pokedoll_swinub"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tadbulb"),
                                            new Identifier(SoulderContent.ID, "pokedoll_taillow"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tandemaus"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tatsugiri"),
                                            new Identifier(SoulderContent.ID, "pokedoll_teddiursa"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tentacool"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tepig"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tinglu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tinkatink"),
                                            new Identifier(SoulderContent.ID, "pokedoll_toedscool"),
                                            new Identifier(SoulderContent.ID, "pokedoll_togepi"),
                                            new Identifier(SoulderContent.ID, "pokedoll_togetic"),
                                            new Identifier(SoulderContent.ID, "pokedoll_torchic"),
                                            new Identifier(SoulderContent.ID, "pokedoll_torkoal"),
                                            new Identifier(SoulderContent.ID, "pokedoll_totodile"),
                                            new Identifier(SoulderContent.ID, "pokedoll_toucannon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tranquill"),
                                            new Identifier(SoulderContent.ID, "pokedoll_trapinch"),
                                            new Identifier(SoulderContent.ID, "pokedoll_treecko"),
                                            new Identifier(SoulderContent.ID, "pokedoll_trubbish"),
                                            new Identifier(SoulderContent.ID, "pokedoll_trumbeak"),
                                            new Identifier(SoulderContent.ID, "pokedoll_turtwig"),
                                            new Identifier(SoulderContent.ID, "pokedoll_typhlosion"),
                                            new Identifier(SoulderContent.ID, "pokedoll_tyrogue"),
                                            new Identifier(SoulderContent.ID, "pokedoll_unown"),
                                            new Identifier(SoulderContent.ID, "pokedoll_ursaring"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vanillite"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vaporeon"),
                                            new Identifier(SoulderContent.ID, "pokedoll_varoom"),
                                            new Identifier(SoulderContent.ID, "pokedoll_veluza"),
                                            new Identifier(SoulderContent.ID, "pokedoll_venonat"),
                                            new Identifier(SoulderContent.ID, "pokedoll_venusaur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vibrava"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vigoroth"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vileplume"),
                                            new Identifier(SoulderContent.ID, "pokedoll_voltorb"),
                                            new Identifier(SoulderContent.ID, "pokedoll_vulpix"),
                                            new Identifier(SoulderContent.ID, "pokedoll_walking_wake"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wartortle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_watchog"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wattrel"),
                                            new Identifier(SoulderContent.ID, "pokedoll_weedle"),
                                            new Identifier(SoulderContent.ID, "pokedoll_weepinbell"),
                                            new Identifier(SoulderContent.ID, "pokedoll_whismur"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wigglytuff"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wiglett"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wingull"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wobbuffet"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wochien"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wooper"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wurmple"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wynaut"),
                                            new Identifier(SoulderContent.ID, "pokedoll_wyrdeer"),
                                            new Identifier(SoulderContent.ID, "pokedoll_xatu"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zebstrika"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zeraora"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zeraora_gilded"),
                                            new Identifier(SoulderContent.ID, "pokedoll_zigzagoon"),
                                            // Мобы
                                            new Identifier(SoulderContent.ID, "allay_plushie"),
                                            new Identifier(SoulderContent.ID, "armadillo_plushie"),
                                            new Identifier(SoulderContent.ID, "axolotl_plushie"),
                                            new Identifier(SoulderContent.ID, "bat_plushie"),
                                            new Identifier(SoulderContent.ID, "bee_plushie"),
                                            new Identifier(SoulderContent.ID, "black_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "black_horse_plushie"),
                                            new Identifier(SoulderContent.ID, "black_n_white_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "black_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "blaze_plushie"),
                                            new Identifier(SoulderContent.ID, "blue_axolotl_plushie"),
                                            new Identifier(SoulderContent.ID, "blue_parrot_plushie"),
                                            new Identifier(SoulderContent.ID, "breeze_plushie"),
                                            new Identifier(SoulderContent.ID, "british_shorthair_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "brown_axolotl_plushie"),
                                            new Identifier(SoulderContent.ID, "calico_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "camel_plushie"),
                                            new Identifier(SoulderContent.ID, "cat_plushie"),
                                            new Identifier(SoulderContent.ID, "cave_spider_plushie"),
                                            new Identifier(SoulderContent.ID, "chestnut_horse_plushie"),
                                            new Identifier(SoulderContent.ID, "chicken_plushie"),
                                            new Identifier(SoulderContent.ID, "cow_plushie"),
                                            new Identifier(SoulderContent.ID, "creeper_plushie"),
                                            new Identifier(SoulderContent.ID, "cyan_axolotl_plushie"),
                                            new Identifier(SoulderContent.ID, "cyan_parrot_plushie"),
                                            new Identifier(SoulderContent.ID, "dolphin_plushie"),
                                            new Identifier(SoulderContent.ID, "donkey_plushie"),
                                            new Identifier(SoulderContent.ID, "drowned_plushie"),
                                            new Identifier(SoulderContent.ID, "elder_guardian_plushie"),
                                            new Identifier(SoulderContent.ID, "enderdragon_plushie"),
                                            new Identifier(SoulderContent.ID, "enderman_plushie"),
                                            new Identifier(SoulderContent.ID, "evoker_plushie"),
                                            new Identifier(SoulderContent.ID, "fox_plushie"),
                                            new Identifier(SoulderContent.ID, "frog_plushie"),
                                            new Identifier(SoulderContent.ID, "frosty_plushie"),
                                            new Identifier(SoulderContent.ID, "ghast_plushie"),
                                            new Identifier(SoulderContent.ID, "gingerbread_man_plushie"),
                                            new Identifier(SoulderContent.ID, "glow_squid_plushie"),
                                            new Identifier(SoulderContent.ID, "goat_plushie"),
                                            new Identifier(SoulderContent.ID, "gold_axolotl_plushie"),
                                            new Identifier(SoulderContent.ID, "gold_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "gray_horse_plushie"),
                                            new Identifier(SoulderContent.ID, "gray_parrot_plushie"),
                                            new Identifier(SoulderContent.ID, "green_parrot_plushie"),
                                            new Identifier(SoulderContent.ID, "guardian_plushie"),
                                            new Identifier(SoulderContent.ID, "hoglin_plushie"),
                                            new Identifier(SoulderContent.ID, "horse_plushie"),
                                            new Identifier(SoulderContent.ID, "husk_plushie"),
                                            new Identifier(SoulderContent.ID, "iron_golem_plushie"),
                                            new Identifier(SoulderContent.ID, "jellie_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "llama_plushie"),
                                            new Identifier(SoulderContent.ID, "magma_cube_plushie"),
                                            new Identifier(SoulderContent.ID, "mooshroom_plushie"),
                                            new Identifier(SoulderContent.ID, "mrs_claus_plushie"),
                                            new Identifier(SoulderContent.ID, "mule_plushie"),
                                            new Identifier(SoulderContent.ID, "panda_plushie"),
                                            new Identifier(SoulderContent.ID, "parrot_plushie"),
                                            new Identifier(SoulderContent.ID, "penguin_plushie"),
                                            new Identifier(SoulderContent.ID, "persian_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "phantom_plushie"),
                                            new Identifier(SoulderContent.ID, "pig_plushie"),
                                            new Identifier(SoulderContent.ID, "piglin_brute_plushie"),
                                            new Identifier(SoulderContent.ID, "piglin_plushie"),
                                            new Identifier(SoulderContent.ID, "pillager_plushie"),
                                            new Identifier(SoulderContent.ID, "polar_bear_plushie"),
                                            new Identifier(SoulderContent.ID, "pufferfish_plushie"),
                                            new Identifier(SoulderContent.ID, "rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "ragdoll_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "ravager_plushie"),
                                            new Identifier(SoulderContent.ID, "red_elf_plushie"),
                                            new Identifier(SoulderContent.ID, "reindeer_plushie"),
                                            new Identifier(SoulderContent.ID, "robin_plushie"),
                                            new Identifier(SoulderContent.ID, "rudolph_plushie"),
                                            new Identifier(SoulderContent.ID, "salt_n_pepper_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "santa_plushie"),
                                            new Identifier(SoulderContent.ID, "sheep_plushie"),
                                            new Identifier(SoulderContent.ID, "shulker_plushie"),
                                            new Identifier(SoulderContent.ID, "siamese_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "skeleton_horse_plushie"),
                                            new Identifier(SoulderContent.ID, "skeleton_plushie"),
                                            new Identifier(SoulderContent.ID, "slime_plushie"),
                                            new Identifier(SoulderContent.ID, "sniffer_plushie"),
                                            new Identifier(SoulderContent.ID, "snow_fox_plushie"),
                                            new Identifier(SoulderContent.ID, "spider_plushie"),
                                            new Identifier(SoulderContent.ID, "squid_plushie"),
                                            new Identifier(SoulderContent.ID, "stray_plushie"),
                                            new Identifier(SoulderContent.ID, "strider_plushie"),
                                            new Identifier(SoulderContent.ID, "tabby_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "temperate_frog_plushie"),
                                            new Identifier(SoulderContent.ID, "toast_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "trader_llama_plushie"),
                                            new Identifier(SoulderContent.ID, "turtle_plushie"),
                                            new Identifier(SoulderContent.ID, "tuxedo_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "vex_plushie"),
                                            new Identifier(SoulderContent.ID, "villager_plushie"),
                                            new Identifier(SoulderContent.ID, "vindicator_plushie"),
                                            new Identifier(SoulderContent.ID, "wandering_trader_plushie"),
                                            new Identifier(SoulderContent.ID, "warden_plushie"),
                                            new Identifier(SoulderContent.ID, "warm_frog_plushie"),
                                            new Identifier(SoulderContent.ID, "white_cat_plushie"),
                                            new Identifier(SoulderContent.ID, "white_horse_plushie"),
                                            new Identifier(SoulderContent.ID, "white_rabbit_plushie"),
                                            new Identifier(SoulderContent.ID, "witch_plushie"),
                                            new Identifier(SoulderContent.ID, "wither_plushie"),
                                            new Identifier(SoulderContent.ID, "wither_skeleton_plushie"),
                                            new Identifier(SoulderContent.ID, "wolf_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_angel_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_baymax_armored_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_baymax_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_buzz_lightyear_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_duchess_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_eve_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_goofy_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_jack_skellington_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_lady_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_light_fury_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_lightning_mcqueen_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_mater_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_mike_wazowski_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_olaf_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_oogie_boogie_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_pluto_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_pumba_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_stitch_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_sully_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_sven_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_thomas_omalley_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_timon_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_toothless_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_tramp_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_walle_plushie"),
                                            new Identifier(SoulderContent.ID, "xmas_woody_plushie"),
                                            new Identifier(SoulderContent.ID, "yellow_elf_plushie"),
                                            new Identifier(SoulderContent.ID, "zoglin_plushie"),
                                            new Identifier(SoulderContent.ID, "zombie_plushie"),
                                            new Identifier(SoulderContent.ID, "zombie_villager_plushie"),

                                            // добавьте остальные ID по необходимости
                                    };

                                    for (Identifier itemID : itemIDs) {
                                        var item = Registries.ITEM.get(itemID);

                                        // Проверяем, что предмет существует, прежде чем добавлять его
                                        if (item != null) {
                                            entries.add(item.getDefaultStack());
                                            LOGGER.warn("Предмет с ID " + itemID + " не найден в реестре.");
                                        }
                                    }
                                })
                                .build())
        );
    }



    @SubscribeEvent
    public void registerBlocks(RegisterEvent event) {
        SoulderBlocks blocks = SoulderBlocks.getInstance();
        event.register(blocks.getRegistryKey(), helper -> blocks.register(helper::register));
    }
}
