package com.soulderspace.souldercontent.block;

import com.soulderspace.souldercontent.RegistryProvider;
import com.soulderspace.souldercontent.block.custom.*;
import net.minecraft.block.Block;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;
import org.jetbrains.annotations.Nullable;

import java.util.Map;

public class SoulderBlocks extends RegistryProvider<Registry<Block>, RegistryKey<Registry<Block>>, Block> {
    private static final SoulderBlocks INSTANCE = new SoulderBlocks();

    public final Block NORMAL_CHEST = crateBlock("normal_chest", true);
    public final Block MEDIUM_CHEST = crateBlock("medium_chest", true);
    public final Block PREMIUM_CHEST = crateBlock("premium_chest", true);
    public final Block BLACK_SILVER_CRATE = crateBlock("black_silver_crate", false);
    public final Block BLUE_LIGHT_BLUE_CRATE = crateBlock("blue_light_blue_crate", false);
    public final Block BROWN_SILVER_CRATE = crateBlock("brown_silver_crate", false);
    public final Block HALLOWEEN_CRATE = crateBlock("halloween_crate", false);
    public final Block PINK_GREEN_CRATE = crateBlock("pink_green_crate", false);
    public final Block PURPLE_LIGHT_PURPLE_CRATE = crateBlock("purple_light_purple_crate", false);
    public final Block RED_GOLDEN_CRATE = crateBlock("red_golden_crate", false);
    public final Block ZOMBIEFIED_PIGLIN_PLUSHIE = pokedoll_BLOCK("zombified_piglin_plushie");
    public final Block POKEDOLL_ZUBAT = pokedoll_BLOCK("pokedoll_zubat");
    public final Block POKEDOLL_MEWTWO_GILDED = pokedoll_BLOCK("pokedoll_mewtwo_gilded");
    public final Block POKEDOLL_MELOETTA = pokedoll_BLOCK("pokedoll_meloetta");
    public final Block POKEDOLL_ZUBAT_SHINY = pokedoll_BLOCK("pokedoll_zubat_shiny");
    public final Block POKEDOLL_MEWTWO_GILDED_SHINY = pokedoll_BLOCK("pokedoll_mewtwo_gilded_shiny");
    public final Block POKEDOLL_MELOETTA_SHINY = pokedoll_BLOCK("pokedoll_meloetta_shiny");

    public final Block POKEDOLL_BIG_GIRATINA = pokedoll_BLOCK("pokedoll_big_giratina");
    public final Block POKEDOLL_CUBONE = pokedoll_BLOCK("pokedoll_cubone");
    public final Block POKEDOLL_ESPEON = pokedoll_BLOCK("pokedoll_espeon");
    public final Block POKEDOLL_GENGAR = pokedoll_BLOCK("pokedoll_gengar");
    public final Block POKEDOLL_GOLBAT = pokedoll_BLOCK("pokedoll_golbat");
    public final Block POKEDOLL_HOUNDOOM = pokedoll_BLOCK("pokedoll_houndoom");
    public final Block POKEDOLL_HOUNDOUR = pokedoll_BLOCK("pokedoll_houndour");
    public final Block POKEDOLL_LITWICK = pokedoll_BLOCK("pokedoll_litwick");
    public final Block POKEDOLL_MAROWAK = pokedoll_BLOCK("pokedoll_marowak");
    public final Block POKEDOLL_UMBREON = pokedoll_BLOCK("pokedoll_umbreon");
    public final Block POKEDOLL_ZORUA = pokedoll_BLOCK("pokedoll_zorua");

    public final Block POKEDOLL_BIG_GIRATINA_SHINY = pokedoll_BLOCK("pokedoll_big_giratina_shiny");
    public final Block POKEDOLL_CUBONE_SHINY = pokedoll_BLOCK("pokedoll_cubone_shiny");
    public final Block POKEDOLL_ESPEON_SHINY = pokedoll_BLOCK("pokedoll_espeon_shiny");
    public final Block POKEDOLL_GENGAR_SHINY = pokedoll_BLOCK("pokedoll_gengar_shiny");
    public final Block POKEDOLL_GOLBAT_SHINY = pokedoll_BLOCK("pokedoll_golbat_shiny");
    public final Block POKEDOLL_HOUNDOOM_SHINY = pokedoll_BLOCK("pokedoll_houndoom_shiny");
    public final Block POKEDOLL_HOUNDOUR_SHINY = pokedoll_BLOCK("pokedoll_houndour_shiny");
    public final Block POKEDOLL_LITWICK_SHINY = pokedoll_BLOCK("pokedoll_litwick_shiny");
    public final Block POKEDOLL_MAROWAK_SHINY = pokedoll_BLOCK("pokedoll_marowak_shiny");
    public final Block POKEDOLL_UMBREON_SHINY = pokedoll_BLOCK("pokedoll_umbreon_shiny");
    public final Block POKEDOLL_ZORUA_SHINY = pokedoll_BLOCK("pokedoll_zorua_shiny");

    public final Block POKEDOLL_ABRA = pokedoll_BLOCK("pokedoll_abra");
    public final Block POKEDOLL_AERODACTYL = pokedoll_BLOCK("pokedoll_aerodactyl");
    public final Block POKEDOLL_AIPOM = pokedoll_BLOCK("pokedoll_aipom");
    public final Block POKEDOLL_AMPHAROS = pokedoll_BLOCK("pokedoll_ampharos");
    public final Block POKEDOLL_APPLIN = pokedoll_BLOCK("pokedoll_applin");
    public final Block POKEDOLL_ARBOK = pokedoll_BLOCK("pokedoll_arbok");
    public final Block POKEDOLL_ARCTIBAX = pokedoll_BLOCK("pokedoll_arctibax");
    public final Block POKEDOLL_ARIADOS = pokedoll_BLOCK("pokedoll_ariados");
    public final Block POKEDOLL_ARON = pokedoll_BLOCK("pokedoll_aron");
    public final Block POKEDOLL_AZUMARILL = pokedoll_BLOCK("pokedoll_azumarill");
    public final Block POKEDOLL_BALTOY = pokedoll_BLOCK("pokedoll_baltoy");
    public final Block POKEDOLL_BAYLEEF = pokedoll_BLOCK("pokedoll_bayleef");
    public final Block POKEDOLL_BELDUM = pokedoll_BLOCK("pokedoll_beldum");
    public final Block POKEDOLL_BELLIBOLT = pokedoll_BLOCK("pokedoll_bellibolt");
    public final Block POKEDOLL_BELLSPROUT = pokedoll_BLOCK("pokedoll_bellsprout");
    public final Block POKEDOLL_BIBAREL = pokedoll_BLOCK("pokedoll_bibarel");
    public final Block POKEDOLL_BIDOOF = pokedoll_BLOCK("pokedoll_bidoof");
    public final Block POKEDOLL_BIG_DIALGA = pokedoll_BLOCK("pokedoll_big_dialga");
    public final Block POKEDOLL_BIG_HOOH = pokedoll_BLOCK("pokedoll_big_hooh");
    public final Block POKEDOLL_BIG_PALKIA = pokedoll_BLOCK("pokedoll_big_palkia");
    public final Block POKEDOLL_BLASTOISE = pokedoll_BLOCK("pokedoll_blastoise");
    public final Block POKEDOLL_BLITZLE = pokedoll_BLOCK("pokedoll_blitzle");
    public final Block POKEDOLL_BONSLY = pokedoll_BLOCK("pokedoll_bonsly");
    public final Block POKEDOLL_BRELOOM = pokedoll_BLOCK("pokedoll_breloom");
    public final Block POKEDOLL_BUIZEL = pokedoll_BLOCK("pokedoll_buizel");
    public final Block POKEDOLL_BULBASAUR = pokedoll_BLOCK("pokedoll_bulbasaur");
    public final Block POKEDOLL_BUNEARY = pokedoll_BLOCK("pokedoll_buneary");
    public final Block POKEDOLL_BUNNELBY = pokedoll_BLOCK("pokedoll_bunnelby");
    public final Block POKEDOLL_BURMY = pokedoll_BLOCK("pokedoll_burmy");
    public final Block POKEDOLL_BUTTERFREE = pokedoll_BLOCK("pokedoll_butterfree");
    public final Block POKEDOLL_CAMERUPT = pokedoll_BLOCK("pokedoll_camerupt");
    public final Block POKEDOLL_CAPSAKID = pokedoll_BLOCK("pokedoll_capsakid");
    public final Block POKEDOLL_CASTFORM = pokedoll_BLOCK("pokedoll_castform");
    public final Block POKEDOLL_CASTFORM_SUNNY = pokedoll_BLOCK("pokedoll_castform_sunny");
    public final Block POKEDOLL_CATERPIE = pokedoll_BLOCK("pokedoll_caterpie");
    public final Block POKEDOLL_CELEBI = pokedoll_BLOCK("pokedoll_celebi");
    public final Block POKEDOLL_CETODDLE = pokedoll_BLOCK("pokedoll_cetoddle");
    public final Block POKEDOLL_CHARIZARD = pokedoll_BLOCK("pokedoll_charizard");
    public final Block POKEDOLL_CHARMANDER = pokedoll_BLOCK("pokedoll_charmander");
    public final Block POKEDOLL_CHARMELEON = pokedoll_BLOCK("pokedoll_charmeleon");
    public final Block POKEDOLL_CHATOT = pokedoll_BLOCK("pokedoll_chatot");
    public final Block POKEDOLL_CHERUBI = pokedoll_BLOCK("pokedoll_cherubi");
    public final Block POKEDOLL_CHESPIN = pokedoll_BLOCK("pokedoll_chespin");
    public final Block POKEDOLL_CHIENPAO = pokedoll_BLOCK("pokedoll_chienpao");
    public final Block POKEDOLL_CHIKORITA = pokedoll_BLOCK("pokedoll_chikorita");
    public final Block POKEDOLL_CHIMCHAR = pokedoll_BLOCK("pokedoll_chimchar");
    public final Block POKEDOLL_CHINCHOU = pokedoll_BLOCK("pokedoll_chinchou");
    public final Block POKEDOLL_CHIYU = pokedoll_BLOCK("pokedoll_chiyu");
    public final Block POKEDOLL_CLEFABLE = pokedoll_BLOCK("pokedoll_clefable");
    public final Block POKEDOLL_CLEFAIRY = pokedoll_BLOCK("pokedoll_clefairy");
    public final Block POKEDOLL_CLEFFA = pokedoll_BLOCK("pokedoll_cleffa");
    public final Block POKEDOLL_CLODSIRE = pokedoll_BLOCK("pokedoll_clodsire");
    public final Block POKEDOLL_COMBUSKEN = pokedoll_BLOCK("pokedoll_combusken");
    public final Block POKEDOLL_CROCALOR = pokedoll_BLOCK("pokedoll_crocalor");
    public final Block POKEDOLL_CROCONAW = pokedoll_BLOCK("pokedoll_croconaw");
    public final Block POKEDOLL_CYNDAQUIL = pokedoll_BLOCK("pokedoll_cyndaquil");
    public final Block POKEDOLL_DACHSBUN = pokedoll_BLOCK("pokedoll_dachsbun");
    public final Block POKEDOLL_DARUMAKA = pokedoll_BLOCK("pokedoll_darumaka");
    public final Block POKEDOLL_DEDENNE = pokedoll_BLOCK("pokedoll_dedenne");
    public final Block POKEDOLL_DELCATTY = pokedoll_BLOCK("pokedoll_delcatty");
    public final Block POKEDOLL_DEWGONG = pokedoll_BLOCK("pokedoll_dewgong");
    public final Block POKEDOLL_DEWOTT = pokedoll_BLOCK("pokedoll_dewott");
    public final Block POKEDOLL_DIGLETT = pokedoll_BLOCK("pokedoll_diglett");
    public final Block POKEDOLL_DIPPLIN = pokedoll_BLOCK("pokedoll_dipplin");
    public final Block POKEDOLL_DITTO = pokedoll_BLOCK("pokedoll_ditto");
    public final Block POKEDOLL_DODUO = pokedoll_BLOCK("pokedoll_doduo");
    public final Block POKEDOLL_DONDOZO = pokedoll_BLOCK("pokedoll_dondozo");
    public final Block POKEDOLL_DRAGONAIR = pokedoll_BLOCK("pokedoll_dragonair");
    public final Block POKEDOLL_DRAGONITE = pokedoll_BLOCK("pokedoll_dragonite");
    public final Block POKEDOLL_DRATINI = pokedoll_BLOCK("pokedoll_dratini");
    public final Block POKEDOLL_DREEPY = pokedoll_BLOCK("pokedoll_dreepy");
    public final Block POKEDOLL_DRILBUR = pokedoll_BLOCK("pokedoll_drilbur");
    public final Block POKEDOLL_DROWZEE = pokedoll_BLOCK("pokedoll_drowzee");
    public final Block POKEDOLL_DUCKLETT = pokedoll_BLOCK("pokedoll_ducklett");
    public final Block POKEDOLL_DUGTRIO = pokedoll_BLOCK("pokedoll_dugtrio");
    public final Block POKEDOLL_DUNSPARCE = pokedoll_BLOCK("pokedoll_dunsparce");
    public final Block POKEDOLL_EEVEE = pokedoll_BLOCK("pokedoll_eevee");
    public final Block POKEDOLL_EISCUE = pokedoll_BLOCK("pokedoll_eiscue");
    public final Block POKEDOLL_EKANS = pokedoll_BLOCK("pokedoll_ekans");
    public final Block POKEDOLL_ELECTRODE = pokedoll_BLOCK("pokedoll_electrode");
    public final Block POKEDOLL_ELEKID = pokedoll_BLOCK("pokedoll_elekid");
    public final Block POKEDOLL_ELGYEM = pokedoll_BLOCK("pokedoll_elgyem");
    public final Block POKEDOLL_ESPURR = pokedoll_BLOCK("pokedoll_espurr");
    public final Block POKEDOLL_EXCADRILL = pokedoll_BLOCK("pokedoll_excadrill");
    public final Block POKEDOLL_EXEGGCUTE = pokedoll_BLOCK("pokedoll_exeggcute");
    public final Block POKEDOLL_EXEGGUTOR = pokedoll_BLOCK("pokedoll_exeggutor");
    public final Block POKEDOLL_FARIGIRAF = pokedoll_BLOCK("pokedoll_farigiraf");
    public final Block POKEDOLL_FEAROW = pokedoll_BLOCK("pokedoll_fearow");
    public final Block POKEDOLL_FEMALE_NIDORAN = pokedoll_BLOCK("pokedoll_female_nidoran");
    public final Block POKEDOLL_FENNEKIN = pokedoll_BLOCK("pokedoll_fennekin");
    public final Block POKEDOLL_FERALIGATR = pokedoll_BLOCK("pokedoll_feraligatr");
    public final Block POKEDOLL_FIDOUGH = pokedoll_BLOCK("pokedoll_fidough");
    public final Block POKEDOLL_FINIZEN = pokedoll_BLOCK("pokedoll_finizen");
    public final Block POKEDOLL_FINNEON = pokedoll_BLOCK("pokedoll_finneon");
    public final Block POKEDOLL_FLAAFFY = pokedoll_BLOCK("pokedoll_flaaffy");
    public final Block POKEDOLL_FLAMIGO = pokedoll_BLOCK("pokedoll_flamigo");
    public final Block POKEDOLL_FLAREON = pokedoll_BLOCK("pokedoll_flareon");
    public final Block POKEDOLL_FLETCHINDER = pokedoll_BLOCK("pokedoll_fletchinder");
    public final Block POKEDOLL_FLETCHLING = pokedoll_BLOCK("pokedoll_fletchling");
    public final Block POKEDOLL_FLOATZEL = pokedoll_BLOCK("pokedoll_floatzel");
    public final Block POKEDOLL_FLYGON = pokedoll_BLOCK("pokedoll_flygon");
    public final Block POKEDOLL_FRIGIBAX = pokedoll_BLOCK("pokedoll_frigibax");
    public final Block POKEDOLL_FROAKIE = pokedoll_BLOCK("pokedoll_froakie");
    public final Block POKEDOLL_FROGADIER = pokedoll_BLOCK("pokedoll_frogadier");
    public final Block POKEDOLL_FUECOCO = pokedoll_BLOCK("pokedoll_fuecoco");
    public final Block POKEDOLL_FURRET = pokedoll_BLOCK("pokedoll_furret");
    public final Block POKEDOLL_GARBODOR = pokedoll_BLOCK("pokedoll_garbodor");
    public final Block POKEDOLL_GEODUDE = pokedoll_BLOCK("pokedoll_geodude");
    public final Block POKEDOLL_GHOLDENGO = pokedoll_BLOCK("pokedoll_gholdengo");
    public final Block POKEDOLL_GIRAFARIG = pokedoll_BLOCK("pokedoll_girafarig");
    public final Block POKEDOLL_GLASTRIER = pokedoll_BLOCK("pokedoll_glastrier");
    public final Block POKEDOLL_GLOOM = pokedoll_BLOCK("pokedoll_gloom");
    public final Block POKEDOLL_GOLDUCK = pokedoll_BLOCK("pokedoll_golduck");
    public final Block POKEDOLL_GOLEM = pokedoll_BLOCK("pokedoll_golem");
    public final Block POKEDOLL_GOTHITA = pokedoll_BLOCK("pokedoll_gothita");
    public final Block POKEDOLL_GRAFAIAI = pokedoll_BLOCK("pokedoll_grafaiai");
    public final Block POKEDOLL_GRANBULL = pokedoll_BLOCK("pokedoll_granbull");
    public final Block POKEDOLL_GRAVELER = pokedoll_BLOCK("pokedoll_graveler");
    public final Block POKEDOLL_GREEDENT = pokedoll_BLOCK("pokedoll_greedent");
    public final Block POKEDOLL_GROOKEY = pokedoll_BLOCK("pokedoll_grookey");
    public final Block POKEDOLL_GROUDON = pokedoll_BLOCK("pokedoll_groudon");
    public final Block POKEDOLL_GROUDON_GILDED = pokedoll_BLOCK("pokedoll_groudon_gilded");
    public final Block POKEDOLL_GROVYLE = pokedoll_BLOCK("pokedoll_grovyle");
    public final Block POKEDOLL_GROWLITHE = pokedoll_BLOCK("pokedoll_growlithe");
    public final Block POKEDOLL_GRUBBIN = pokedoll_BLOCK("pokedoll_grubbin");
    public final Block POKEDOLL_GRUMPIG = pokedoll_BLOCK("pokedoll_grumpig");
    public final Block POKEDOLL_GULPIN = pokedoll_BLOCK("pokedoll_gulpin");
    public final Block POKEDOLL_HALLOWEEN_BULBASAUR = pokedoll_BLOCK("pokedoll_halloween_bulbasaur");
    public final Block POKEDOLL_HALLOWEEN_IVYSAUR = pokedoll_BLOCK("pokedoll_halloween_ivysaur");
    public final Block POKEDOLL_HALLOWEEN_VENUSAUR = pokedoll_BLOCK("pokedoll_halloween_venusaur");
    public final Block POKEDOLL_HERACROSS = pokedoll_BLOCK("pokedoll_heracross");
    public final Block POKEDOLL_HITMONLEE = pokedoll_BLOCK("pokedoll_hitmonlee");
    public final Block POKEDOLL_HOOH = pokedoll_BLOCK("pokedoll_hooh");
    public final Block POKEDOLL_HOOTHOOT = pokedoll_BLOCK("pokedoll_hoothoot");
    public final Block POKEDOLL_HOPPIP = pokedoll_BLOCK("pokedoll_hoppip");
    public final Block POKEDOLL_HYPNO = pokedoll_BLOCK("pokedoll_hypno");
    public final Block POKEDOLL_IGGLYBUFF = pokedoll_BLOCK("pokedoll_igglybuff");
    public final Block POKEDOLL_IMPIDIMP = pokedoll_BLOCK("pokedoll_impidimp");
    public final Block POKEDOLL_IRON_BUNDLE = pokedoll_BLOCK("pokedoll_iron_bundle");
    public final Block POKEDOLL_IRONVALIANT = pokedoll_BLOCK("pokedoll_ironvaliant");
    public final Block POKEDOLL_IVYSAUR = pokedoll_BLOCK("pokedoll_ivysaur");
    public final Block POKEDOLL_JIGGLYPUFF = pokedoll_BLOCK("pokedoll_jigglypuff");
    public final Block POKEDOLL_JIRACHI = pokedoll_BLOCK("pokedoll_jirachi");
    public final Block POKEDOLL_JOLTEON = pokedoll_BLOCK("pokedoll_jolteon");
    public final Block POKEDOLL_KILOWATTREL = pokedoll_BLOCK("pokedoll_kilowattrel");
    public final Block POKEDOLL_KORAIDON = pokedoll_BLOCK("pokedoll_koraidon");
    public final Block POKEDOLL_KRICKETOT = pokedoll_BLOCK("pokedoll_kricketot");
    public final Block POKEDOLL_KROKOROK = pokedoll_BLOCK("pokedoll_krokorok");
    public final Block POKEDOLL_KROOKODILE = pokedoll_BLOCK("pokedoll_krookodile");
    public final Block POKEDOLL_KYOGRE = pokedoll_BLOCK("pokedoll_kyogre");
    public final Block POKEDOLL_KYOGRE_GILDED = pokedoll_BLOCK("pokedoll_kyogre_gilded");
    public final Block POKEDOLL_LANTURN = pokedoll_BLOCK("pokedoll_lanturn");
    public final Block POKEDOLL_LARVITAR = pokedoll_BLOCK("pokedoll_larvitar");
    public final Block POKEDOLL_LATIAS = pokedoll_BLOCK("pokedoll_latias");
    public final Block POKEDOLL_LATIOS = pokedoll_BLOCK("pokedoll_latios");
    public final Block POKEDOLL_LECHONK = pokedoll_BLOCK("pokedoll_lechonk");
    public final Block POKEDOLL_LEDIAN = pokedoll_BLOCK("pokedoll_ledian");
    public final Block POKEDOLL_LEDYBA = pokedoll_BLOCK("pokedoll_ledyba");
    public final Block POKEDOLL_LILLIPUP = pokedoll_BLOCK("pokedoll_lillipup");
    public final Block POKEDOLL_LINOONE = pokedoll_BLOCK("pokedoll_linoone");
    public final Block POKEDOLL_LITLEO = pokedoll_BLOCK("pokedoll_litleo");
    public final Block POKEDOLL_LITTEN = pokedoll_BLOCK("pokedoll_litten");
    public final Block POKEDOLL_LOTAD = pokedoll_BLOCK("pokedoll_lotad");
    public final Block POKEDOLL_LOUDRED = pokedoll_BLOCK("pokedoll_loudred");
    public final Block POKEDOLL_LUCARIO = pokedoll_BLOCK("pokedoll_lucario");
    public final Block POKEDOLL_LUGIA = pokedoll_BLOCK("pokedoll_lugia");
    public final Block POKEDOLL_LUMINEON = pokedoll_BLOCK("pokedoll_lumineon");
    public final Block POKEDOLL_LUXIO = pokedoll_BLOCK("pokedoll_luxio");
    public final Block POKEDOLL_MABOSSTIFF = pokedoll_BLOCK("pokedoll_mabosstiff");
    public final Block POKEDOLL_MACHOP = pokedoll_BLOCK("pokedoll_machop");
    public final Block POKEDOLL_MAGBY = pokedoll_BLOCK("pokedoll_magby");
    public final Block POKEDOLL_MAGCARGO = pokedoll_BLOCK("pokedoll_magcargo");
    public final Block POKEDOLL_MAGIKARP = pokedoll_BLOCK("pokedoll_magikarp");
    public final Block POKEDOLL_MAGNEMITE = pokedoll_BLOCK("pokedoll_magnemite");
    public final Block POKEDOLL_MALE_NIDORAN = pokedoll_BLOCK("pokedoll_male_nidoran");
    public final Block POKEDOLL_MAMOSWINE = pokedoll_BLOCK("pokedoll_mamoswine");
    public final Block POKEDOLL_MANAPHY = pokedoll_BLOCK("pokedoll_manaphy");
    public final Block POKEDOLL_MANKEY = pokedoll_BLOCK("pokedoll_mankey");
    public final Block POKEDOLL_MANTINE = pokedoll_BLOCK("pokedoll_mantine");
    public final Block POKEDOLL_MANTYKE = pokedoll_BLOCK("pokedoll_mantyke");
    public final Block POKEDOLL_MAREEP = pokedoll_BLOCK("pokedoll_mareep");
    public final Block POKEDOLL_MARILL = pokedoll_BLOCK("pokedoll_marill");
    public final Block POKEDOLL_MARSHTOMP = pokedoll_BLOCK("pokedoll_marshtomp");
    public final Block POKEDOLL_MASCHIFF = pokedoll_BLOCK("pokedoll_maschiff");
    public final Block POKEDOLL_MASQUERAIN = pokedoll_BLOCK("pokedoll_masquerain");
    public final Block POKEDOLL_MEDITITE = pokedoll_BLOCK("pokedoll_meditite");
    public final Block POKEDOLL_MEGANIUM = pokedoll_BLOCK("pokedoll_meganium");
    public final Block POKEDOLL_MEOWTH = pokedoll_BLOCK("pokedoll_meowth");
    public final Block POKEDOLL_METAGROSS = pokedoll_BLOCK("pokedoll_metagross");
    public final Block POKEDOLL_METANG = pokedoll_BLOCK("pokedoll_metang");
    public final Block POKEDOLL_METAPOD = pokedoll_BLOCK("pokedoll_metapod");
    public final Block POKEDOLL_MEW = pokedoll_BLOCK("pokedoll_mew");
    public final Block POKEDOLL_MEWTWO = pokedoll_BLOCK("pokedoll_mewtwo");
    public final Block POKEDOLL_MILTANK = pokedoll_BLOCK("pokedoll_miltank");
    public final Block POKEDOLL_MIME_JR = pokedoll_BLOCK("pokedoll_mime_jr");
    public final Block POKEDOLL_MINCCINO = pokedoll_BLOCK("pokedoll_minccino");
    public final Block POKEDOLL_MINIOR = pokedoll_BLOCK("pokedoll_minior");
    public final Block POKEDOLL_MINUN = pokedoll_BLOCK("pokedoll_minun");
    public final Block POKEDOLL_MIRAIDON = pokedoll_BLOCK("pokedoll_miraidon");
    public final Block POKEDOLL_MONFERNO = pokedoll_BLOCK("pokedoll_monferno");
    public final Block POKEDOLL_MORPEKO = pokedoll_BLOCK("pokedoll_morpeko");
    public final Block POKEDOLL_MR_MIME = pokedoll_BLOCK("pokedoll_mr_mime");
    public final Block POKEDOLL_MR_RIME = pokedoll_BLOCK("pokedoll_mr_rime");
    public final Block POKEDOLL_MUDKIP = pokedoll_BLOCK("pokedoll_mudkip");
    public final Block POKEDOLL_MUNNA = pokedoll_BLOCK("pokedoll_munna");
    public final Block POKEDOLL_MURKROW = pokedoll_BLOCK("pokedoll_murkrow");
    public final Block POKEDOLL_NACLI = pokedoll_BLOCK("pokedoll_nacli");
    public final Block POKEDOLL_NATU = pokedoll_BLOCK("pokedoll_natu");
    public final Block POKEDOLL_NICKIT = pokedoll_BLOCK("pokedoll_nickit");
    public final Block POKEDOLL_NINETALES = pokedoll_BLOCK("pokedoll_ninetales");
    public final Block POKEDOLL_NOCTOWL = pokedoll_BLOCK("pokedoll_noctowl");
    public final Block POKEDOLL_NUMEL = pokedoll_BLOCK("pokedoll_numel");
    public final Block POKEDOLL_NUZLEAF = pokedoll_BLOCK("pokedoll_nuzleaf");
    public final Block POKEDOLL_OCTILLERY = pokedoll_BLOCK("pokedoll_octillery");
    public final Block POKEDOLL_ODDISH = pokedoll_BLOCK("pokedoll_oddish");
    public final Block POKEDOLL_OINKOLOGNE = pokedoll_BLOCK("pokedoll_oinkologne");
    public final Block POKEDOLL_ORTHWORM = pokedoll_BLOCK("pokedoll_orthworm");
    public final Block POKEDOLL_OSHAWOTT = pokedoll_BLOCK("pokedoll_oshawott");
    public final Block POKEDOLL_PACHIRISU = pokedoll_BLOCK("pokedoll_pachirisu");
    public final Block POKEDOLL_PANPOUR = pokedoll_BLOCK("pokedoll_panpour");
    public final Block POKEDOLL_PANSAGE = pokedoll_BLOCK("pokedoll_pansage");
    public final Block POKEDOLL_PANSEAR = pokedoll_BLOCK("pokedoll_pansear");
    public final Block POKEDOLL_PARAS = pokedoll_BLOCK("pokedoll_paras");
    public final Block POKEDOLL_PARASECT = pokedoll_BLOCK("pokedoll_parasect");
    public final Block POKEDOLL_PATRAT = pokedoll_BLOCK("pokedoll_patrat");
    public final Block POKEDOLL_PAWMI = pokedoll_BLOCK("pokedoll_pawmi");
    public final Block POKEDOLL_PAWMO = pokedoll_BLOCK("pokedoll_pawmo");
    public final Block POKEDOLL_PAWMOT = pokedoll_BLOCK("pokedoll_pawmot");
    public final Block POKEDOLL_PERSIAN = pokedoll_BLOCK("pokedoll_persian");
    public final Block POKEDOLL_PHANPY = pokedoll_BLOCK("pokedoll_phanpy");
    public final Block POKEDOLL_PHIONE = pokedoll_BLOCK("pokedoll_phione");
    public final Block POKEDOLL_PICHU = pokedoll_BLOCK("pokedoll_pichu");
    public final Block POKEDOLL_PIDGEOTTO = pokedoll_BLOCK("pokedoll_pidgeotto");
    public final Block POKEDOLL_PIDGEY = pokedoll_BLOCK("pokedoll_pidgey");
    public final Block POKEDOLL_PIDOVE = pokedoll_BLOCK("pokedoll_pidove");
    public final Block POKEDOLL_PIGNITE = pokedoll_BLOCK("pokedoll_pignite");
    public final Block POKEDOLL_PIKACHU = pokedoll_BLOCK("pokedoll_pikachu");
    public final Block POKEDOLL_PIKIPEK = pokedoll_BLOCK("pokedoll_pikipek");
    public final Block POKEDOLL_PILOSWINE = pokedoll_BLOCK("pokedoll_piloswine");
    public final Block POKEDOLL_PIPLUP = pokedoll_BLOCK("pokedoll_piplup");
    public final Block POKEDOLL_PLUSLE = pokedoll_BLOCK("pokedoll_plusle");
    public final Block POKEDOLL_POLITOED = pokedoll_BLOCK("pokedoll_politoed");
    public final Block POKEDOLL_POLIWAG = pokedoll_BLOCK("pokedoll_poliwag");
    public final Block POKEDOLL_POLIWHIRL = pokedoll_BLOCK("pokedoll_poliwhirl");
    public final Block POKEDOLL_POLIWRATH = pokedoll_BLOCK("pokedoll_poliwrath");
    public final Block POKEDOLL_PONYTA = pokedoll_BLOCK("pokedoll_ponyta");
    public final Block POKEDOLL_POOCHYENA = pokedoll_BLOCK("pokedoll_poochyena");
    public final Block POKEDOLL_POPPLIO = pokedoll_BLOCK("pokedoll_popplio");
    public final Block POKEDOLL_PORYGON = pokedoll_BLOCK("pokedoll_porygon");
    public final Block POKEDOLL_PORYGON_2 = pokedoll_BLOCK("pokedoll_porygon_2");
    public final Block POKEDOLL_PRIMEAPE = pokedoll_BLOCK("pokedoll_primeape");
    public final Block POKEDOLL_PRINPLUP = pokedoll_BLOCK("pokedoll_prinplup");
    public final Block POKEDOLL_PSYDUCK = pokedoll_BLOCK("pokedoll_psyduck");
    public final Block POKEDOLL_QUAGSIRE = pokedoll_BLOCK("pokedoll_quagsire");
    public final Block POKEDOLL_QUAXLY = pokedoll_BLOCK("pokedoll_quaxly");
    public final Block POKEDOLL_QUILAVA = pokedoll_BLOCK("pokedoll_quilava");
    public final Block POKEDOLL_QUILLADIN = pokedoll_BLOCK("pokedoll_quilladin");
    public final Block POKEDOLL_QWILFISH = pokedoll_BLOCK("pokedoll_qwilfish");
    public final Block POKEDOLL_RAICHU = pokedoll_BLOCK("pokedoll_raichu");
    public final Block POKEDOLL_RALTS = pokedoll_BLOCK("pokedoll_ralts");
    public final Block POKEDOLL_RAPIDASH = pokedoll_BLOCK("pokedoll_rapidash");
    public final Block POKEDOLL_RATICATE = pokedoll_BLOCK("pokedoll_raticate");
    public final Block POKEDOLL_RATTATA = pokedoll_BLOCK("pokedoll_rattata");
    public final Block POKEDOLL_RAYQUAZA = pokedoll_BLOCK("pokedoll_rayquaza");
    public final Block POKEDOLL_RAYQUAZA_GILDED = pokedoll_BLOCK("pokedoll_rayquaza_gilded");
    public final Block POKEDOLL_REGISTEEL = pokedoll_BLOCK("pokedoll_registeel");
    public final Block POKEDOLL_RELLOR = pokedoll_BLOCK("pokedoll_rellor");
    public final Block POKEDOLL_REMORAID = pokedoll_BLOCK("pokedoll_remoraid");
    public final Block POKEDOLL_RIOLU = pokedoll_BLOCK("pokedoll_riolu");
    public final Block POKEDOLL_ROARINGMOON = pokedoll_BLOCK("pokedoll_roaringmoon");
    public final Block POKEDOLL_ROCKRUFF = pokedoll_BLOCK("pokedoll_rockruff");
    public final Block POKEDOLL_ROGGENROLA = pokedoll_BLOCK("pokedoll_roggenrola");
    public final Block POKEDOLL_ROOKIDEE = pokedoll_BLOCK("pokedoll_rookidee");
    public final Block POKEDOLL_ROTOM = pokedoll_BLOCK("pokedoll_rotom");
    public final Block POKEDOLL_ROWLET = pokedoll_BLOCK("pokedoll_rowlet");
    public final Block POKEDOLL_SABLEYE = pokedoll_BLOCK("pokedoll_sableye");
    public final Block POKEDOLL_SANDILE = pokedoll_BLOCK("pokedoll_sandile");
    public final Block POKEDOLL_SANDSHREW = pokedoll_BLOCK("pokedoll_sandshrew");
    public final Block POKEDOLL_SANDSLASH = pokedoll_BLOCK("pokedoll_sandslash");
    public final Block POKEDOLL_SCORBUNNY = pokedoll_BLOCK("pokedoll_scorbunny");
    public final Block POKEDOLL_SCRAFTY = pokedoll_BLOCK("pokedoll_scrafty");
    public final Block POKEDOLL_SCRAGGY = pokedoll_BLOCK("pokedoll_scraggy");
    public final Block POKEDOLL_SCREAM_TAIL = pokedoll_BLOCK("pokedoll_scream_tail");
    public final Block POKEDOLL_SCYTHER = pokedoll_BLOCK("pokedoll_scyther");
    public final Block POKEDOLL_SEALEO = pokedoll_BLOCK("pokedoll_sealeo");
    public final Block POKEDOLL_SEEDOT = pokedoll_BLOCK("pokedoll_seedot");
    public final Block POKEDOLL_SEEL = pokedoll_BLOCK("pokedoll_seel");
    public final Block POKEDOLL_SENTRET = pokedoll_BLOCK("pokedoll_sentret");
    public final Block POKEDOLL_SERVINE = pokedoll_BLOCK("pokedoll_servine");
    public final Block POKEDOLL_SHARPEDO = pokedoll_BLOCK("pokedoll_sharpedo");
    public final Block POKEDOLL_SHAYMIN = pokedoll_BLOCK("pokedoll_shaymin");
    public final Block POKEDOLL_SHINX = pokedoll_BLOCK("pokedoll_shinx");
    public final Block POKEDOLL_SHROODLE = pokedoll_BLOCK("pokedoll_shroodle");
    public final Block POKEDOLL_SHROOMISH = pokedoll_BLOCK("pokedoll_shroomish");
    public final Block POKEDOLL_SHUCKLE = pokedoll_BLOCK("pokedoll_shuckle");
    public final Block POKEDOLL_SILCOON = pokedoll_BLOCK("pokedoll_silcoon");
    public final Block POKEDOLL_SKIPLOOM = pokedoll_BLOCK("pokedoll_skiploom");
    public final Block POKEDOLL_SKITTY = pokedoll_BLOCK("pokedoll_skitty");
    public final Block POKEDOLL_SKWOVET = pokedoll_BLOCK("pokedoll_skwovet");
    public final Block POKEDOLL_SLAKOTH = pokedoll_BLOCK("pokedoll_slakoth");
    public final Block POKEDOLL_SLOWPOKE = pokedoll_BLOCK("pokedoll_slowpoke");
    public final Block POKEDOLL_SLUGMA = pokedoll_BLOCK("pokedoll_slugma");
    public final Block POKEDOLL_SMEARGLE = pokedoll_BLOCK("pokedoll_smeargle");
    public final Block POKEDOLL_SMOLIV = pokedoll_BLOCK("pokedoll_smoliv");
    public final Block POKEDOLL_SMOOCHUM = pokedoll_BLOCK("pokedoll_smoochum");
    public final Block POKEDOLL_SNIVY = pokedoll_BLOCK("pokedoll_snivy");
    public final Block POKEDOLL_SNORLAX = pokedoll_BLOCK("pokedoll_snorlax");
    public final Block POKEDOLL_SNUBBULL = pokedoll_BLOCK("pokedoll_snubbull");
    public final Block POKEDOLL_SOBBLE = pokedoll_BLOCK("pokedoll_sobble");
    public final Block POKEDOLL_SOLOSIS = pokedoll_BLOCK("pokedoll_solosis");
    public final Block POKEDOLL_SPEAROW = pokedoll_BLOCK("pokedoll_spearow");
    public final Block POKEDOLL_SPHEAL = pokedoll_BLOCK("pokedoll_spheal");
    public final Block POKEDOLL_SPINARAK = pokedoll_BLOCK("pokedoll_spinarak");
    public final Block POKEDOLL_SPINDA = pokedoll_BLOCK("pokedoll_spinda");
    public final Block POKEDOLL_SPOINK = pokedoll_BLOCK("pokedoll_spoink");
    public final Block POKEDOLL_SPRIGATITO = pokedoll_BLOCK("pokedoll_sprigatito");
    public final Block POKEDOLL_SQUAWKABILLY = pokedoll_BLOCK("pokedoll_squawkabilly");
    public final Block POKEDOLL_SQUIRTLE = pokedoll_BLOCK("pokedoll_squirtle");
    public final Block POKEDOLL_STANTLER = pokedoll_BLOCK("pokedoll_stantler");
    public final Block POKEDOLL_STARAVIA = pokedoll_BLOCK("pokedoll_staravia");
    public final Block POKEDOLL_STARLY = pokedoll_BLOCK("pokedoll_starly");
    public final Block POKEDOLL_SUDOWOODO = pokedoll_BLOCK("pokedoll_sudowoodo");
    public final Block POKEDOLL_SUICUNE = pokedoll_BLOCK("pokedoll_suicune");
    public final Block POKEDOLL_SUNFLORA = pokedoll_BLOCK("pokedoll_sunflora");
    public final Block POKEDOLL_SURSKIT = pokedoll_BLOCK("pokedoll_surskit");
    public final Block POKEDOLL_SWABLU = pokedoll_BLOCK("pokedoll_swablu");
    public final Block POKEDOLL_SWALOT = pokedoll_BLOCK("pokedoll_swalot");
    public final Block POKEDOLL_SWAMPERT = pokedoll_BLOCK("pokedoll_swampert");
    public final Block POKEDOLL_SWELLOW = pokedoll_BLOCK("pokedoll_swellow");
    public final Block POKEDOLL_SWINUB = pokedoll_BLOCK("pokedoll_swinub");
    public final Block POKEDOLL_TADBULB = pokedoll_BLOCK("pokedoll_tadbulb");
    public final Block POKEDOLL_TAILLOW = pokedoll_BLOCK("pokedoll_taillow");
    public final Block POKEDOLL_TANDEMAUS = pokedoll_BLOCK("pokedoll_tandemaus");
    public final Block POKEDOLL_TATSUGIRI = pokedoll_BLOCK("pokedoll_tatsugiri");
    public final Block POKEDOLL_TEDDIURSA = pokedoll_BLOCK("pokedoll_teddiursa");
    public final Block POKEDOLL_TENTACOOL = pokedoll_BLOCK("pokedoll_tentacool");
    public final Block POKEDOLL_TEPIG = pokedoll_BLOCK("pokedoll_tepig");
    public final Block POKEDOLL_TINGLU = pokedoll_BLOCK("pokedoll_tinglu");
    public final Block POKEDOLL_TINKATINK = pokedoll_BLOCK("pokedoll_tinkatink");
    public final Block POKEDOLL_TOEDSCOOL = pokedoll_BLOCK("pokedoll_toedscool");
    public final Block POKEDOLL_TOGEPI = pokedoll_BLOCK("pokedoll_togepi");
    public final Block POKEDOLL_TOGETIC = pokedoll_BLOCK("pokedoll_togetic");
    public final Block POKEDOLL_TORCHIC = pokedoll_BLOCK("pokedoll_torchic");
    public final Block POKEDOLL_TORKOAL = pokedoll_BLOCK("pokedoll_torkoal");
    public final Block POKEDOLL_TOTODILE = pokedoll_BLOCK("pokedoll_totodile");
    public final Block POKEDOLL_TOUCANNON = pokedoll_BLOCK("pokedoll_toucannon");
    public final Block POKEDOLL_TRANQUILL = pokedoll_BLOCK("pokedoll_tranquill");
    public final Block POKEDOLL_TRAPINCH = pokedoll_BLOCK("pokedoll_trapinch");
    public final Block POKEDOLL_TREECKO = pokedoll_BLOCK("pokedoll_treecko");
    public final Block POKEDOLL_TRUBBISH = pokedoll_BLOCK("pokedoll_trubbish");
    public final Block POKEDOLL_TRUMBEAK = pokedoll_BLOCK("pokedoll_trumbeak");
    public final Block POKEDOLL_TURTWIG = pokedoll_BLOCK("pokedoll_turtwig");
    public final Block POKEDOLL_TYPHLOSION = pokedoll_BLOCK("pokedoll_typhlosion");
    public final Block POKEDOLL_TYROGUE = pokedoll_BLOCK("pokedoll_tyrogue");
    public final Block POKEDOLL_UNOWN = pokedoll_BLOCK("pokedoll_unown");
    public final Block POKEDOLL_URSARING = pokedoll_BLOCK("pokedoll_ursaring");
    public final Block POKEDOLL_VANILLITE = pokedoll_BLOCK("pokedoll_vanillite");
    public final Block POKEDOLL_VAPOREON = pokedoll_BLOCK("pokedoll_vaporeon");
    public final Block POKEDOLL_VAROOM = pokedoll_BLOCK("pokedoll_varoom");
    public final Block POKEDOLL_VELUZA = pokedoll_BLOCK("pokedoll_veluza");
    public final Block POKEDOLL_VENONAT = pokedoll_BLOCK("pokedoll_venonat");
    public final Block POKEDOLL_VENUSAUR = pokedoll_BLOCK("pokedoll_venusaur");
    public final Block POKEDOLL_VIBRAVA = pokedoll_BLOCK("pokedoll_vibrava");
    public final Block POKEDOLL_VIGOROTH = pokedoll_BLOCK("pokedoll_vigoroth");
    public final Block POKEDOLL_VILEPLUME = pokedoll_BLOCK("pokedoll_vileplume");
    public final Block POKEDOLL_VOLTORB = pokedoll_BLOCK("pokedoll_voltorb");
    public final Block POKEDOLL_VULPIX = pokedoll_BLOCK("pokedoll_vulpix");
    public final Block POKEDOLL_WALKING_WAKE = pokedoll_BLOCK("pokedoll_walking_wake");
    public final Block POKEDOLL_WARTORTLE = pokedoll_BLOCK("pokedoll_wartortle");
    public final Block POKEDOLL_WATCHOG = pokedoll_BLOCK("pokedoll_watchog");
    public final Block POKEDOLL_WATTREL = pokedoll_BLOCK("pokedoll_wattrel");
    public final Block POKEDOLL_WEEDLE = pokedoll_BLOCK("pokedoll_weedle");
    public final Block POKEDOLL_WEEPINBELL = pokedoll_BLOCK("pokedoll_weepinbell");
    public final Block POKEDOLL_WHISMUR = pokedoll_BLOCK("pokedoll_whismur");
    public final Block POKEDOLL_WIGGLYTUFF = pokedoll_BLOCK("pokedoll_wigglytuff");
    public final Block POKEDOLL_WIGLETT = pokedoll_BLOCK("pokedoll_wiglett");
    public final Block POKEDOLL_WINGULL = pokedoll_BLOCK("pokedoll_wingull");
    public final Block POKEDOLL_WOBBUFFET = pokedoll_BLOCK("pokedoll_wobbuffet");
    public final Block POKEDOLL_WOCHIEN = pokedoll_BLOCK("pokedoll_wochien");
    public final Block POKEDOLL_WOOPER = pokedoll_BLOCK("pokedoll_wooper");
    public final Block POKEDOLL_WURMPLE = pokedoll_BLOCK("pokedoll_wurmple");
    public final Block POKEDOLL_WYNAUT = pokedoll_BLOCK("pokedoll_wynaut");
    public final Block POKEDOLL_WYRDEER = pokedoll_BLOCK("pokedoll_wyrdeer");
    public final Block POKEDOLL_XATU = pokedoll_BLOCK("pokedoll_xatu");
    public final Block POKEDOLL_ZEBSTRIKA = pokedoll_BLOCK("pokedoll_zebstrika");
    public final Block POKEDOLL_ZERAORA = pokedoll_BLOCK("pokedoll_zeraora");
    public final Block POKEDOLL_ZERAORA_GILDED = pokedoll_BLOCK("pokedoll_zeraora_gilded");
    public final Block POKEDOLL_ZIGZAGOON = pokedoll_BLOCK("pokedoll_zigzagoon");

    public final Block AUTUMN_LEAVES_CARPET = allTypesLeaves("autumn_leaves_carpet");
    public final Block SPIDERWEB_0 = skeletonBlock("spiderweb_0");
    public final Block SPIDERWEB_1 = skeletonBlock("spiderweb_1");
    public final Block SPIDERWEB_2 = skeletonBlock("spiderweb_2");
    public final Block SPIDERWEB_3 = skeletonBlock("spiderweb_3");
    public final Block SPIDERWEB_4 = skeletonBlock("spiderweb_4");

    public final Block CARVED_EVIL_PUMPKIN = crateBlock("carved_evil_pumpkin",false);
    public final Block CARVED_FRIENDLY_PUMPKIN = crateBlock("carved_friendly_pumpkin",false);
    public final Block CARVED_SCREAMING_PUMPKIN = crateBlock("carved_screaming_pumpkin",false);
    public final Block CARVED_SHOCKED_PUMPKIN = crateBlock("carved_shocked_pumpkin",false);
    public final Block CARVED_SMILE_PUMPKIN = crateBlock("carved_smile_pumpkin",false);
    public final Block FLAT_DIRT_GRAVESTONE = gravehorizontal("flat_dirt_gravestone");
    public final Block FLAT_GRAVESTONE = gravehorizontal("flat_gravestone");
    public final Block GRAVESTONE = gravevertical("gravestone");
    public final Block SLANTED_GRAVESTONE = gravesmall("slanted_gravestone");
    public final Block SQUARE_GRAVESTONE = gravevertical("square_gravestone");
    public final Block SMALL_GRAVESTONE = gravesmall("small_gravestone");
    public final Block HAY_WHEELBARROW = crateBlock("hay_wheelbarrow",true);
    public final Block LAYING_HAY_BALE = crateBlock("laying_hay_bale",true);
    public final Block PUMPKIN_WHEELBARROW = crateBlock("pumpkin_wheelbarrow",true);
    public final Block LARGE_PUMPKIN = crateBlock("large_pumpkin",true);
    public final Block SMALL_PUMPKIN = crateBlock("small_pumpkin",true);
    public final Block MEDIUM_PUMPKIN = crateBlock("medium_pumpkin",true);
    public final Block LIT_EVIL_PUMPKIN = pumpkinLight("lit_evil_pumpkin");
    public final Block LIT_FRIENDLY_PUMPKIN = pumpkinLight("lit_friendly_pumpkin");
    public final Block LIT_SCREAMING_PUMPKIN = pumpkinLight("lit_screaming_pumpkin");
    public final Block LIT_SHOCKED_PUMPKIN = pumpkinLight("lit_shocked_pumpkin");
    public final Block LIT_SMILE_PUMPKIN = pumpkinLight("lit_smile_pumpkin");
    public final Block PAIR_OF_PUMPKINS = crateBlock("pair_of_pumpkins",true);
    public final Block PUMPKIN_BALLOON = ballooned("pumpkin_balloon");
    public final Block PUMPKIN_WALL_DECO_1 = walldecoBlock("pumpkin_wall_deco_1");
    public final Block PUMPKIN_WALL_DECO_2 = walldecoBlock("pumpkin_wall_deco_2");
    public final Block SCARECROW = scareCrow("scarecrow");
    public final Block SITTING_SKELETON = skeletonBlock("sitting_skeleton");
    public final Block SKELETON_BALLOON = ballooned("skeleton_balloon");
    public final Block GHOST_BALLOON = ballooned("ghost_balloon");
    public final Block GHOST = ballooned("ghost");
    public final Block THREE_POTIONS = crateBlock("three_potions",true);
    public final Block THREE_PUMPKINS = crateBlock("three_pumpkins",true);
    public final Block WITCH_CAULDRON = crateBlock("witch_cauldron",false);





    public final Block SKELETON_0 = skeletonBlock("skeleton_0");
    public final Block SKELETON_1 = skeletonBlock("skeleton_1");
    public final Block SKELETON_2 = skeletonBlock("skeleton_2");
    public final Block SKELETON_3 = skeletonBlock("skeleton_3");
    public final Block SKELETON_4 = skeletonBlock("skeleton_4");

    public final Block SCARECROW_0_TOP = scareCrow("scarecrow_0_top");
    public final Block SCARECROW_0_BOTTOM = scareCrow("scarecrow_0_bottom");
    public final Block SCARECROW_1_BOTTOM = scareCrow("scarecrow_1_bottom");
    public final Block SCARECROW_1_TOP = scareCrow("scarecrow_1_top");
    public final Block SCARECROW_2_TOP = scareCrow("scarecrow_2_top");
    public final Block SCARECROW_2_BOTTOM = scareCrow("scarecrow_2_bottom");
    public final Block SCARECROW_3_TOP = scareCrow("scarecrow_3_top");
    public final Block SCARECROW_3_BOTTOM = scareCrow("scarecrow_3_bottom");
    public final Block SCARECROW_4_TOP = scareCrow("scarecrow_4_top");
    public final Block SCARECROW_4_BOTTOM = scareCrow("scarecrow_4_bottom");
    public static SoulderBlocks getInstance() {
        return INSTANCE;
    }

    private SoulderBlocks() {}

    private Block crateBlock(String name, boolean small) {
        return block(name, new CrateBlock(small));
    }
    private Block allTypesLeaves(String name){return block(name, new AutumnLeavesCarpetBlock());}
    private Block skullBlock(String name){return block(name, new LeavesBlock());}
    private Block pumpkinLight(String name){return block(name, new pumpkins());}
    private Block pokedoll_BLOCK(String name){return block(name, new Pokedoll());}
    private Block walldecoBlock(String name){return block(name, new wall_deco());}
    private Block gravehorizontal(String name){return block(name, new gravestone_1());}
    private Block gravevertical(String name){return block(name, new gravestone_vertical());}
    private Block gravesmall(String name){return block(name, new gravestone_small());}
    private Block ballooned(String name){return block(name, new balloons());}
    private Block scareCrow(String name){return block(name, new ScarecroweBox());}
    private Block skeletonBlock(String name){return block(name, new SkeletonsBox());}
    private Block block(String name, Block block) {
        return this.add(name, block);
    }

    @Override
    public Registry<Block> getRegistry() {
        return Registries.BLOCK;
    }

    @Override
    public RegistryKey<Registry<Block>> getRegistryKey() {
        return RegistryKeys.BLOCK;
    }

    @Nullable
    public static Identifier getId(Block block) {
        Map.Entry<Identifier, Block> entry = getInstance().queue.entrySet().stream()
                .filter(e -> e.getValue().equals(block)).findFirst().orElse(null);
        if (entry != null) {
            return entry.getKey();
        }
        return null;
    }
}
